### ISSUE TITLE
Permalinks need escaping

### ISSUE THREAD

**Issue by handelaar** [conoro/hugo.conoroneill.net#1]
Hola. You've an entry with a hash in the title and (because anchors) it doesn't load unless you replace that hash with %23

Looking at the repo it seems you noticed something was up already :)

**Comment by conoro** [comment]
Thanks John. I've been meaning to come back to that. Not sure if it's a theme/template bug  or a Hugo bug. Going to just remove hashes in titles for the moment.

**Comment by conoro** [comment]
All posts manually fixed. I'll avoid # in titles from now on :-)
